name: Remote VBS Trigger Workflow

on:
  repository_dispatch:
    types: [run_vbs_trigger]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge Trigger
        run: echo "Trigger received from web interface!"
